### ISSUE TITLE
Missing fame and silver information

### ISSUE THREAD

**Issue by LaionFromNight** [imjangkar/albibong#1]
Missing fame and silver information

```
ERROR on_event: Traceback (most recent call last):
  File "/Users/.../.pyenv/versions/3.9.18/lib/python3.9/site-packages/albibong/classes/packet_handler.py", line 22, in wrapper
    payload = func(*args, **kwargs)
  File "/Users/.../.pyenv/versions/3.9.18/lib/python3.9/site-packages/albibong/classes/packet_handler.py", line 39, in on_event
    self.world_data.handle_event(payload.parameters)
  File "/Users/.../.pyenv/versions/3.9.18/lib/python3.9/site-packages/albibong/classes/world_data.py", line 52, in handle_event
    self.me.update_fame(parameters)
  File "/Users/.../.pyenv/versions/3.9.18/lib/python3.9/site-packages/albibong/classes/character.py", line 47, in update_fame
    fame = parameters[2] / DIVISOR
KeyError: 2
```

also weapon are not displayed  
<img width="740" alt="image" src="https://github.com/imjangkar/albibong/assets/66757837/076fbbdc-0311-4b73-b4f6-c4f8bf6e29b4">

**Comment by LaionFromNight** [comment]
The Issue is on main branch and with package `pip install albibong` after run it branch `patch-3-foundation` all is working fine 

<img width="1112" alt="image" src="https://github.com/imjangkar/albibong/assets/66757837/711aabdd-0b4a-4837-9253-c369f21ad821">
<img width="632" alt="image" src="https://github.com/imjangkar/albibong/assets/66757837/1113df9a-9f16-405e-bc78-cd6e125ec898">
